### ISSUE TITLE
Task2 - Create a rectangle on one lane and draw

### ISSUE THREAD

**Issue by miguelriemoliveira** [miguelriemoliveira/savi_22-23#2]
![highway](https://user-images.githubusercontent.com/11350998/193774724-a62596d3-d50c-43f3-a463-9d278c6a1808.png)

The task is to figure out the coordinates of that rectangle and draw it on image highway.png

**Comment by miguelriemoliveira** [comment]
Now that I think a bit more it would be great to have 4 rectangles one for each lane.

**Comment by miguelriemoliveira** [comment]
Thanks @Rafafbo  for the code.

There is an error at the end of the video:

```
Traceback (most recent call last):
  File "./test_view_video.py", line 29, in <module>
    main()
  File "./test_view_video.py", line 15, in main
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.4) /tmp/pip-req-build-th1mncc2/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

```

**Comment by miguelriemoliveira** [comment]
@Rafafbo don't worry about this . I fixed it. The problem was the place where you put the cvtcolor.

**Comment by miguelriemoliveira** [comment]
I am using the code you sent by email. Thanks.
